# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointmentsmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppointmentsManager',
        ),
    ]
